jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acceso?useTimezone=true&serverTimezone=UTC
    password: Admin_2020
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false